InsuranceAgency.WebUI/Models/ErrorViewModel.cs
using System;

namespace InsuranceAgency.WebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InsuranceAgency.WebUI/Models/LicenseQueryInput.cs
namespace InsuranceAgency.WebUI.Models
{
    public class LicenseQueryInput
    {
        public string Plate { get; set; }

        public string TCId { get; set; }
    }
}

InsuranceAgency.WebUI/Models/OfferQueryInput.cs
using System.ComponentModel.DataAnnotations;

namespace InsuranceAgency.WebUI.Models
{
    public class OfferQueryInput
    {
        [Display(Name = "TC No")]
        public string TCId { get; set; }
    }
}

InsuranceAgency.WebUI/Models/OfferResult.cs
namespace InsuranceAgency.WebUI.Models
{
    public class OfferResult
    {
        public string CompanyName { get; set; }

        public string Logo { get; set; }

        public string Description { get; set; }

        public decimal Amount { get; set; }

        public string Plate { get; set; }
    }
}

InsuranceAgency.WebUI/Models/QuotationCreateInput.cs
using System.ComponentModel.DataAnnotations;

namespace InsuranceAgency.WebUI.Models
{
    public class QuotationCreateInput
    {
        [Display(Name = "Plaka")]
        public string Plate { get; set; }

        [Display(Name = "TC No")]
        public string TCId { get; set; }

        [Display(Name = "Ruhsat Seri Kodu")]
        public string LicenseSerialCode { get; set; }

        [Display(Name = "Ruhsat Seri No")]
        public string LicenseSerialNo { get; set; }
    }
}

InsuranceAgency.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net.Http;
using AutoMapper;
using InsuranceAgency.Business.Dtos;
using InsuranceAgency.Business.Services;
using InsuranceAgency.Provider.Providers;
using InsuranceAgency.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace InsuranceAgency.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IQuotationService _quotationService;
        private readonly IMapper _mapper;
        private readonly IInsuranceProviderService _insuranceProviderService;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IOfferService _offerService;

        public HomeController(ILogger<HomeController> logger, IQuotationService quotationService, IMapper mapper, IInsuranceProviderService insuranceProviderService, IHttpClientFactory httpClientFactory, IOfferService offerService)
        {
            _logger = logger;
            _quotationService = quotationService;
            _mapper = mapper;
            _insuranceProviderService = insuranceProviderService;
            _httpClientFactory = httpClientFactory;
            _offerService = offerService;
        }

        public IActionResult Index()
        {
            var result = _insuranceProviderService.GetAll();

            ViewData["InsuranceProviders"] = result.Data;

            //ViewData["Offers"] = offers.Result.Data;

            return View();
        }

        [HttpPost]
        public IActionResult Index(QuotationCreateInput quotationCreateInput)
        {
            var result = _insuranceProviderService.GetAll();

            ViewData["InsuranceProviders"] = result.Data;

            if (!ModelState.IsValid)
            {
                return View();
            }

            var newData = _mapper.Map<QuotationCreateDto>(quotationCreateInput);
            newData.CreatedAt = DateTime.Now;
            _quotationService.Create(newData);

            List<OfferResult> offerResults = new List<OfferResult>();

            var providerQueryMap = _mapper.Map<ProviderQueryDto>(quotationCreateInput);

            ProviderService providerServiceAcibademSigorta = new(new AcibademSigortaProvider(_httpClientFactory));
            var resultAcibademSigorta = providerServiceAcibademSigorta.GetOffer(providerQueryMap);
            offerResults.Add(_mapper.Map<OfferResult>(resultAcibademSigorta.Data.data));
            _offerService.Create(_mapper.Map<OfferCreateDto>(resultAcibademSigorta.Data.data));

            ProviderService providerServiceAkSigorta = new(new AkSigortaProvider(_httpClientFactory));
            var resultAkSigorta = providerServiceAkSigorta.GetOffer(providerQueryMap);
            offerResults.Add(_mapper.Map<OfferResult>(resultAkSigorta.Data.data));
            _offerService.Create(_mapper.Map<OfferCreateDto>(resultAkSigorta.Data.data));

            ProviderService providerServiceAllianz = new(new AllianzProvider(_httpClientFactory));
            var resultAllianz = providerServiceAllianz.GetOffer(providerQueryMap);
            offerResults.Add(_mapper.Map<OfferResult>(resultAllianz.Data.data));
            _offerService.Create(_mapper.Map<OfferCreateDto>(resultAllianz.Data.data));

            ProviderService providerServiceAnadoluSigorta = new(new AnadoluSigortaProvider(_httpClientFactory));
            var resultAnadoluSigorta = providerServiceAnadoluSigorta.GetOffer(providerQueryMap);
            offerResults.Add(_mapper.Map<OfferResult>(resultAnadoluSigorta.Data.data));
            _offerService.Create(_mapper.Map<OfferCreateDto>(resultAnadoluSigorta.Data.data));

            ViewData["Offers"] = offerResults;

            /*var resultsss = providerService.GetOffer(new ProviderQueryDto()
            {
                Plate = "45ZN447",
                TCId = "62809043732",
                LicenseSerialCode = "AZ",
                LicenseSerialNo = "123456"
            });*/

            return View();
        }

        [HttpPost]
        public JsonResult License(LicenseQueryInput licenseQueryInput)
        {
            var quotationResult = _quotationService.GetByPlateTCId(licenseQueryInput.Plate, licenseQueryInput.TCId);

            return Json(quotationResult);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InsuranceAgency.WebUI/Controllers/OfferController.cs
using InsuranceAgency.Business.Services;
using InsuranceAgency.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace InsuranceAgency.WebUI.Controllers
{
    public class OfferController : Controller
    {
        private readonly IOfferService _offerService;

        public OfferController(IOfferService offerService)
        {
            _offerService = offerService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(OfferQueryInput offerQueryInput)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var result = _offerService.GetAllByTCId(offerQueryInput.TCId);

            ViewData["Offers"] = result.Data;

            return View(offerQueryInput);
        }
    }
}

InsuranceAgency.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Teklif Talep Formu";
}

@model QuotationCreateInput

@{
    List<InsuranceAgency.Business.Dtos.InsuranceProviderDto> insuranceProviders = ViewData["InsuranceProviders"] as List<InsuranceAgency.Business.Dtos.InsuranceProviderDto>;
    List<InsuranceAgency.WebUI.Models.OfferResult> offers = ViewData["Offers"] as List<InsuranceAgency.WebUI.Models.OfferResult>;
}

<div class="card">
    <div class="card-body">
        <form asp-controller="Home" asp-action="Index" method="post">
            <div class="row mb-3">
                <label for="inputPlate" class="col-sm-3 col-form-label" asp-for="Plate"></label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" asp-for="Plate">
                    <span class="text-danger" asp-validation-for="Plate"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputTCId" class="col-sm-3 col-form-label" asp-for="TCId"></label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" asp-for="TCId">
                    <span class="text-danger" asp-validation-for="TCId"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputLicenseSerialCode" class="col-sm-3 col-form-label" asp-for="LicenseSerialCode"></label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" asp-for="LicenseSerialCode">
                    <span class="text-danger" asp-validation-for="LicenseSerialCode"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputLicenseSerialNo" class="col-sm-3 col-form-label" asp-for="LicenseSerialNo"></label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" asp-for="LicenseSerialNo">
                    <span class="text-danger" asp-validation-for="LicenseSerialNo"></span>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Teklif Al</button>
        </form>
    </div>
</div>

@if (offers != null)
{
    if (offers.Any())
    {
        <div class="card mt-3">
            <div class="card-header">
                Sigorta Şirketlerinin Verdiği Teklifler
            </div>
            <div class="card-body">
                <div class="row">
                    <table class="table mb-0">
                        <thead>
                            <tr>
                                <th>Sigorta Firması</th>
                                <th>Teklif Açıklaması</th>
                                <th>Teklif Tutarı</th>
                                <th>Plaka</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var offer in offers)
                            {
                                <tr>
                                    <td><img class="img-fluid" src="@offer.Logo" alt="@offer.CompanyName" /></td>
                                    <td>@offer.Description</td>
                                    <td>@offer.Amount TL</td>
                                    <td>@offer.Plate</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    }
}

<div class="card mt-3">
    <div class="card-header">
        Sigorta Şirketleri
    </div>
    <div class="card-body">
        <div class="row">
            @if (insuranceProviders != null)
            {
                if (insuranceProviders.Any())
                {
                    foreach (var insuranceProvider in insuranceProviders)
                    {
                        <div class="col-3 text-center mb-3"><img class="img-fluid" src="@insuranceProvider.Logo" alt="@insuranceProvider.CompanyName" /></div>

                    }
                }
            }
        </div>
    </div>
</div>

InsuranceAgency.WebUI/Views/Offer/Index.cshtml
@{
    ViewData["Title"] = "Verilen Teklifler";
}

@model OfferQueryInput

@{
    List<InsuranceAgency.Business.Dtos.OfferDto> offers = ViewData["Offers"] as List<InsuranceAgency.Business.Dtos.OfferDto>;
}

<div class="card">
    <div class="card-header">
        Teklif Sorgulama
    </div>
    <div class="card-body">
        <form asp-controller="Offer" asp-action="Index" method="post">
            <div class="row">
                <label for="inputTCId" class="col-sm-2 col-form-label" asp-for="TCId"></label>
                <div class="col-sm-7">
                    <input type="text" class="form-control" asp-for="TCId">
                    <span class="text-danger" asp-validation-for="TCId"></span>
                </div>
                <div class="col-sm-3">
                    <button type="submit" class="btn btn-primary btn-block">ARA</button>
                </div>
            </div>
            
        </form>
    </div>
</div>

@if (offers != null)
{
    <div class="card mt-3">
        <div class="card-header">
            Sigorta Şirketleri Tarafından Verilen Teklifler
        </div>
        <div class="card-body">
            @if (offers.Any())
            {
                <table class="table mb-0">
                    <thead>
                        <tr>
                            <th>Sigorta Firması</th>
                            <th>Teklif Açıklaması</th>
                            <th>Teklif Tutarı</th>
                            <th>Plaka</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var offer in offers)
                        {
                            <tr>
                                <td><img class="img-fluid" src="@offer.Logo" alt="@offer.CompanyName" /></td>
                                <td>@offer.Description</td>
                                <td>@offer.Amount TL</td>
                                <td>@offer.Plate</td>
                            </tr>
                        }

                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-info mb-0" role="alert">
                    Bu kimlik numarasına ait verilmiş teklif yoktur.
                </div>
            }

        </div>
    </div>
}

InsuranceAgency.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InsuranceAgency.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InsuranceAgency.WebUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="container">
                <div class="row">
                    <div class="col-3">
                        <div class="list-group">
                            <a class="list-group-item list-group-item-action" asp-area="" asp-controller="Home" asp-action="Index">Teklif Talep Formu</a>
                            <a class="list-group-item list-group-item-action" asp-area="" asp-controller="Offer" asp-action="Index">Verilen Teklifler</a>
                        </div>
                    </div>
                    <div class="col-9">
                        @RenderBody()
                    </div>
                </div>
            </div>
            
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - InsuranceAgency.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>